name = "AMORS"
uuid = "77d29c75-3847-48dd-b74a-66585bbee1d5"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[compat]
TypeUtils = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
