name = "AMORS"
uuid = "77d29c75-3847-48dd-b74a-66585bbee1d5"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.1.0"

[deps]
Unitless = "c904d999-9673-4878-a3dd-e3ef1851788a"

[compat]
Unitless = "2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
